server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql:///xdb
    username: root
    password: 1234
  redis:
    port: 6379
    host: localhost
logging:
  level:
    com.xpker: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.xpker.*.entity
